# wordpress/templates/deployment-wordpress.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
spec:
  replicas: {{ .Values.wordpress.replicaCount }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: "{{ .Values.wordpress.image.repository }}:{{ .Values.wordpress.image.tag }}"
          imagePullPolicy: {{ .Values.wordpress.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: "mariadb"  # MariaDB service name
            - name: WORDPRESS_DB_NAME
              value: "{{ .Values.mariadb.db.name }}"
            - name: WORDPRESS_DB_USER
              value: "{{ .Values.mariadb.db.user }}"
            - name: WORDPRESS_DB_PASSWORD
              value: "{{ .Values.mariadb.db.password }}"