# wordpress/templates/service-wordpress.yaml
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress
spec:
  type: {{ .Values.wordpress.service.type }}
  ports:
    - port: {{ .Values.wordpress.service.port }}
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32001
  selector:
    app: wordpress